curl -s localhost:11635/peers | jq ".peers | length"
curl -s localhost:12635/peers | jq ".peers | length"
curl -s localhost:13635/peers | jq ".peers | length"
curl -s localhost:14635/peers | jq ".peers | length"
curl -s localhost:15635/peers | jq ".peers | length"
curl -s localhost:16635/peers | jq ".peers | length"
curl -s localhost:17635/peers | jq ".peers | length"
curl -s localhost:18635/peers | jq ".peers | length"
curl -s localhost:19635/peers | jq ".peers | length"
curl -s localhost:20635/peers | jq ".peers | length"
curl -s localhost:21635/peers | jq ".peers | length"
curl -s localhost:22635/peers | jq ".peers | length"
curl -s localhost:23635/peers | jq ".peers | length"
curl -s localhost:24635/peers | jq ".peers | length"
curl -s localhost:25635/peers | jq ".peers | length"

