version: "3"

services:
  clef-9:
    image: ethersphere/clef:0.4.12
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=5
    volumes:
      - clef-9:/app/data
    command: full

  bee-9:
    image: ethersphere/bee:0.6.2
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-9:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE=true
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD=hexacube
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_RESOLVER_OPTIONS
      - BEE_STANDALONE
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT=wss://goerli.infura.io/ws/v3/030d9a8d196e49f5a6580114da570b17
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_INITIAL_DEPOSIT=1000000000000000
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE="Hexacube bzz node 1"
    ports:
      - "${API_ADDR:-19633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-19634}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-19635}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - bee-9:/home/bee/.bee
    command: start
    depends_on:
      - clef-9
volumes:
  clef-9:
  bee-9:
